theme = "catppuccin_mocha"

[editor]
cursorline = true
gutters = ["diagnostics", "line-numbers"]
line-number = "relative"
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.normal]
C-s = ":w" # Save file

[keys.normal.space]
# Replace File Explorer with yazi
e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

[keys.normal.space.g]
d = [":new", ":insert-output lazydocker", ":buffer-close!", ":redraw"]
g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all"]

[keys.insert]
C-s = ["normal_mode", ":w"] # Enter normal mode and save file

[keys.select]
C-s = [":w"] # Enter normal mode and save file
