#!/bin/bash

wttr() {
  local location="${1// /+}"
  test "$#" -gt 0 && shift
  local args=()
  curl -fGsS -H "Accept-Language: ${LANG%_*}" "${args[@]}" --compressed "wttr.in/${location}"
}

wttr "$@"
